-- POKRETANJE: db2 -td@ -f create.sql
-- -td@ da bi @ bio delimiter 

--CREATE  SCHEMA MG@

DROP TABLE MG.PREDMET@

CREATE TABLE MG.PREDMET(
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 1),
	NAZIV CHAR(50) NOT NULL,
	OZNAKA CHAR(5) NOT NULL,
	SEMESTAR INT,
	KATEDRA CHAR,
	ESPB INT,
	PRIMARY KEY (ID),
	CONSTRAINT KATEDRACHK CHECK (KATEDRA IN ('M', 'I'))
)@
		
	
DROP TABLE MG.STUDENT@
	
CREATE TABLE MG.STUDENT(
	INDEKS CHAR(10) NOT NULL,
	IME CHAR(50) NOT NULL,
	PREZIME CHAR(50) NOT NULL,
	POL CHAR,
	PRIMARY KEY (INDEKS),
	CONSTRAINT POLK CHECK (POL IN ('M', 'Z'))
)@


DROP TABLE MG.ISPIT@

CREATE TABLE MG.ISPIT(
	INDEKS CHAR(10) NOT NULL,
	IDPREDMETA INT NOT NULL,
	POENI FLOAT,
	OCENA INT,
	DATUM DATE,
	CONSTRAINT POENICHK CHECK (POENI BETWEEN 0 AND 100),
	CONSTRAINT OCENACHK CHECK (OCENA BETWEEN 5 AND 10),
	PRIMARY KEY (INDEKS, IDPREDMETA),
	FOREIGN KEY PREDMETFK (IDPREDMETA) 
		REFERENCES MG.PREDMET ON DELETE NO ACTION,
	FOREIGN KEY INDEKSFK (INDEKS) 
		REFERENCES MG.STUDENT ON DELETE CASCADE -- NO ACTION
)@



CREATE OR REPLACE TRIGGER DUPLI_UNOS_ISPITA
	BEFORE INSERT ON MG.ISPIT
	REFERENCING NEW AS N 
	FOR EACH ROW
	BEGIN
	
	DELETE FROM MG.ISPIT I
	WHERE I.INDEKS=N.INDEKS AND I.IDPREDMETA = N.IDPREDMETA;
	
	END@

--SET TERMINATOR ;

